language: cpp
dist: trusty
sudo: required

addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0
    - ubuntu-toolchain-r-test

# Install gcc-7 from a PPA to get a recent libstdc++
before_install:
  - sudo apt-get clean
  - sudo apt-get update -q
  - sudo apt-get install clang-5.0 gcc-7 g++-7 -y

install:
  - export CXX="clang++-5.0" CC="clang-5.0"

before_script:
  - mkdir build && cd build
  - cmake ..

script:
  - cmake --build . && cmake --build . --target test
