name: Build and Deploy Doxygen

on:
  push:
    paths:
      - 'docs/**'
      - 'lib-vs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build and Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          submodules: recursive
      - run: |
          echo '::echo::on'
          echo "PROJECT_NUMBER = `git describe --tags`" >> ./docs/doxygen/Doxyfile
      - run: sudo apt-get install -y doxygen graphviz
      - run: doxygen ./docs/doxygen/Doxyfile
      - uses: actions/upload-pages-artifact@main
        with:
          path: './docs/html'

  deploy:
    name: Deploy to GH-Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@main
        with:
          emit_telemetry: true
          conclusion: success
      - id: deployment
        uses: actions/deploy-pages@main